language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sapui5' ]; then cd .. && eval "mv $currentfolder generator-sapui5" && cd generator-sapui5; fi

